[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

[deploy]
healthcheckPath = "/health"

healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "api"
source = "backend"

[[services]]
name = "frontend"
source = "frontend"
