[build]
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"


[[services]]
name = "api"
source = "backend"

[[services]]
name = "frontend"
source = "frontend"
