"""documents_and_vouchers

Revision ID: 2d4e4efa8ba2
Revises: 946039096edd
Create Date: 2026-05-01 23:08:01.367948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4e4efa8ba2'
down_revision: Union[str, Sequence[str], None] = '946039096edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_original', sa.String(length=300), nullable=False),
    sa.Column('nombre_storage', sa.String(length=300), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('tamaño_bytes', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=30), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('subido_por', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de creación'),
    sa.CheckConstraint("tipo_documento IN ('boleta', 'factura', 'estado_cuenta_bancario', 'acta_reunion', 'foto', 'otro')", name='check_tipo_documento'),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_documentos',
    sa.Column('movimiento_id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos.id'], ),
    sa.PrimaryKeyConstraint('movimiento_id', 'documento_id')
    )
    op.create_table('vales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('movimiento_id', sa.Uuid(), nullable=False),
    sa.Column('concepto', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('recibe_nombre', sa.String(length=200), nullable=True),
    sa.Column('entrega_nombre', sa.String(length=200), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('pdf_storage_key', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('anulado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de creación'),
    sa.CheckConstraint("tipo IN ('ingreso', 'egreso')", name='check_vale_tipo'),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_index('idx_vales_folio', 'vales', ['folio'], unique=False)
    op.create_table('comprobantes_pago',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('pago_cuota_id', sa.Uuid(), nullable=False),
    sa.Column('alumno_id', sa.Uuid(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('recibido_por', sa.Uuid(), nullable=False),
    sa.Column('recibido_por_nombre', sa.String(length=200), nullable=False),
    sa.Column('qr_verification_url', sa.Text(), nullable=False),
    sa.Column('pdf_storage_key', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('hash_pdf', sa.String(length=64), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('anulado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de creación'),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['pago_cuota_id'], ['pagos_cuota.id'], ),
    sa.ForeignKeyConstraint(['recibido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    op.create_index('idx_comprobantes_folio', 'comprobantes_pago', ['folio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_comprobantes_folio', table_name='comprobantes_pago')
    op.drop_table('comprobantes_pago')
    op.drop_index('idx_vales_folio', table_name='vales')
    op.drop_table('vales')
    op.drop_table('movimiento_documentos')
    op.drop_table('documentos')
    # ### end Alembic commands ###
