"""communications_tables

Revision ID: 5083ab50e6c7
Revises: 2d4e4efa8ba2
Create Date: 2026-05-01 23:28:07.129898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5083ab50e6c7'
down_revision: Union[str, Sequence[str], None] = '2d4e4efa8ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantillas_email',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('asunto_template', sa.String(length=300), nullable=False),
    sa.Column('cuerpo_html_template', sa.Text(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.CheckConstraint("tipo IN ('comprobante_pago', 'estado_cuenta', 'recordatorio_cuota', 'bienvenida')", name='check_plantilla_tipo'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails_enviados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('alumno_id', sa.Uuid(), nullable=True),
    sa.Column('apoderado_id', sa.Uuid(), nullable=True),
    sa.Column('destinatario_email', sa.String(length=200), nullable=False),
    sa.Column('destinatario_nombre', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('asunto', sa.String(length=300), nullable=False),
    sa.Column('cuerpo_html', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('resend_message_id', sa.String(length=100), nullable=True),
    sa.Column('error_detalle', sa.Text(), nullable=True),
    sa.Column('adjunto_storage_key', sa.Text(), nullable=True),
    sa.Column('enviado_por', sa.Uuid(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('ultimo_intento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.CheckConstraint("estado IN ('pendiente', 'enviado', 'fallido', 'rebotado')", name='check_email_estado'),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['apoderado_id'], ['apoderados.id'], ),
    sa.ForeignKeyConstraint(['enviado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails_enviados')
    op.drop_table('plantillas_email')
    # ### end Alembic commands ###
