"""reports_and_conciliation

Revision ID: 8278e4698bc7
Revises: 5083ab50e6c7
Create Date: 2026-05-01 23:33:57.203089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8278e4698bc7'
down_revision: Union[str, Sequence[str], None] = '5083ab50e6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierres_año',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('año_cierre', sa.Integer(), nullable=False),
    sa.Column('saldo_final', sa.Integer(), nullable=False),
    sa.Column('saldo_traspasado', sa.Integer(), nullable=False),
    sa.Column('año_destino', sa.Integer(), nullable=True),
    sa.Column('resumen_json', sa.JSON(), nullable=False),
    sa.Column('aprobado_por', sa.Uuid(), nullable=True),
    sa.Column('aprobado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acta_storage_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conciliaciones_bancarias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=True),
    sa.Column('saldo_inicial', sa.Integer(), nullable=False),
    sa.Column('saldo_final', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('archivo_storage_key', sa.Text(), nullable=True),
    sa.Column('conciliado_por', sa.Uuid(), nullable=True),
    sa.Column('conciliado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.ForeignKeyConstraint(['conciliado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presupuesto_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('monto_proyectado', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_movimiento.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporte_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('resultado_storage_key', sa.Text(), nullable=True),
    sa.Column('resultado_url', sa.Text(), nullable=True),
    sa.Column('error_detalle', sa.Text(), nullable=True),
    sa.Column('solicitado_por', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_bancarias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conciliacion_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('saldo_banco', sa.Integer(), nullable=True),
    sa.Column('movimiento_id', sa.Uuid(), nullable=True),
    sa.Column('conciliada', sa.Boolean(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.ForeignKeyConstraint(['conciliacion_id'], ['conciliaciones_bancarias.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineas_bancarias')
    op.drop_table('reporte_jobs')
    op.drop_table('presupuesto_items')
    op.drop_table('conciliaciones_bancarias')
    op.drop_table('cierres_año')
    # ### end Alembic commands ###
