"""add_conciliado_to_movimientos

Revision ID: 9d5eebb8fce7
Revises: 8278e4698bc7
Create Date: 2026-05-01 23:35:14.279171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5eebb8fce7'
down_revision: Union[str, Sequence[str], None] = '8278e4698bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimientos', sa.Column('conciliado', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimientos', 'conciliado')
    # ### end Alembic commands ###
