"""audit_log_table

Revision ID: df337ae56662
Revises: 9d5eebb8fce7
Create Date: 2026-05-01 23:48:39.360670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df337ae56662'
down_revision: Union[str, Sequence[str], None] = '9d5eebb8fce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.String(length=50), nullable=True),
    sa.Column('payload_antes', sa.JSON(), nullable=True),
    sa.Column('payload_despues', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de eliminación lógica'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
